// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcuabojivzvpphmvztes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjdWFib2ppdnp2cHBobXZ6dGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDc1NTQsImV4cCI6MjA2NTc4MzU1NH0.0APKAv4lbrew63VPrxqBf5O9OwpZw7Ulxr7RE3hraN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});